[package]
name = "autoimpl-derive"
version = "0.1.0"
authors = ["Blake Pettersson <blake.pettersson@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.11", features = ["full"] }
quote = "0.3"
proc-macro-hack = "0.3"
